server:
  port: 8001
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
  servlet:
    context-path: /evac
spring:
    profiles:
          active: dev
    freemarker:
      suffix: .html
      request-context-attribute: request