server:
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
  servlet:
    context-path: /evac

spring:
    profiles:
          active: test
    freemarker:
      suffix: .html
      request-context-attribute: request
    application:
      name: eva-client
#feign断路器开关
feign:
  hystrix:
    enabled: true;


logging:
  path: logs/
  file: eva-client.log
  level:
    root: info
    io.renren.service.EvaluteFeignService: DEBUG
