dictionary:
    cache-type: cache_redis
    statement: io.renren.modules.sys.dao.SysDictDao.executeSelectExtraDictSql
    #sys_dict以外需要放入缓存中的数据
    extra-dict:
        ryxx: select info_id as code , info_title as value from tbl_info
        xxfb : select person_id as code, person_name as value from tbl_person