# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    servlet:
        context-path: /eva

# mysql
spring:
    # 环境 dev|test|prod
    profiles:
        active: test
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    redis:
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
    freemarker:
      suffix: .html
      request-context-attribute: request
    #messageSourse 验证
    messages:
      basename: ValidationMessages
      encoding: UTF-8
    application:
      name: eva-admin

renren:
  cluster: false  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  globalSessionTimeout: 3600   #单机环境，session过期时间为60分钟
  redis:
    open: true  #是否开启redis缓存  true开启   false关闭

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: io.renren.modules.*.entity
  global-config:
    db-config:
      db-type: mysql
      #主键类型
      id-type: AUTO
      #字段策略
      field-strategy: NOT_NULL
      #驼峰下划线转换
      #db-column-underline: true
      #刷新mapper 调试神器
      #refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

#服务注册中心配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eva/eureka/
#  instance:
#    metadata-map:
#      info1: test1
#      info2: test2

logging:
  level: debug
  level.io.renren: debug
  path: logs/
  file: eva-admin.log

#皮肤 AdminLTE & Layui
skin: AdminLTE


#数据字典配置
dictionary:
    cache-type: redis
    statement: io.renren.modules.sys.dao.SysDictDao.executeSelectExtraDictSql
    extra-dict:
        zdlx : select type as code , name as value from sys_dict where del_flag = 0 group by type, name;
        gglx : select data_no as code, type_name as value from bte_lesson_type where category_id = 1 and del_flag != -1
        zylx : select data_no as code, type_name as value from bte_lesson_type where category_id = 2 and del_flag != -1
#    code: dict_value
#    type: dict_type
#    value: dict_name
#    property-type: dictType