dictionary:
    statement: io.renren.modules.sys.dao.SysDictDao.excuteSelectExtraDictSql
    #sys_dict以外需要放入缓存中的数据
    extra-open: false
    extra-dict:
        gglx:  select data_no as code, type_name as value from bte_lesson_type where category_id = 1 and del_flag != -1
        zylx : select data_no as code, type_name as value from bte_lesson_type where category_id = 2 and del_flag != -1